# Generated by Django 4.2.8 on 2024-02-05 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_storyprofile_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='last_updated',
            field=models.TimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 5, 17, 48, 50, 20862, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
