# Generated by Django 4.2.8 on 2024-02-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_story_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='last_updated',
        ),
    ]
